AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - tiantian_li.me::my-profile-backend-serverless
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  MyProfileBackendServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: tiantian_li.me.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MyProfileBackendServerlessApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: MyProfileBackendServerlessApi
