name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Backend setup
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '22'

    - name: Build Backend
      env:
        DB_HOST: ${{ secrets.RDS_HOST }}
        DB_PORT: ${{ secrets.RDS_PORT }}
        DB_NAME: ${{ secrets.RDS_DB_NAME }}
        DB_USER: ${{ secrets.RDS_USERNAME }}
        DB_PASSWORD: ${{ secrets.RDS_PASSWORD }}
      run: |
        cd my-profile-backend
        ./gradlew clean build --warning-mode all

    - name: Run Backend Tests
      env:
        DB_HOST: ${{ secrets.RDS_HOST }}
        DB_PORT: ${{ secrets.RDS_PORT }}
        DB_NAME: ${{ secrets.RDS_DB_NAME }}
        DB_USER: ${{ secrets.RDS_USERNAME }}
        DB_PASSWORD: ${{ secrets.RDS_PASSWORD }}
      run: |
        cd my-profile-backend
        ./gradlew test

    # Frontend setup
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Frontend Dependencies
      run: |
        cd my-profile-frontend
        npm install

    - name: Build Frontend with Vite
      run: |
        cd my-profile-frontend
        npm run build

    - name: Run Frontend Tests
      run: |
        cd my-profile-frontend
        npm run test

    - name: Deploy Backend to AWS EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
        chmod 400 ec2_key.pem
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
          ls
          pm2 list
          pm2 restart my-profile-backend
          pm2 list
        EOF

